// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type ExchangeRate struct {
	ID         int64
	Code       string
	Codein     string
	Name       string
	High       float64
	Low        float64
	Varbid     float64
	Pctchange  float64
	Bid        float64
	Ask        float64
	Timestamp  int64
	CreateDate string
}
